server:
  port: 8081
  url: '/'

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/pmi?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB


file-save-path: E:/pmi/images/ #文件上传的保存位置

mybatis:
  mapper-locations: classpath*:mapper/*.xml #Mybatis扫描
  type-aliases-package: com.yicao.pmiapi.pojo #起别名。可省略写mybatis的xml中的resultType的全路径

# 日志配置
logging:
  level:
    com.yicao.pmiapi.mapper: debug

# jwt配置
jwt:
  # 存储的请求头
  tokenHeader: Authorization
  # 密钥
  secret: yeb-secret
  # 过期时间 单位s
  expiration: 604800
  # 负载的开头
  tokenHead: Bearer

# MybatisEplus配置
mybatis-plus:
  # 配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置lyBatis数据返回类型别名(默认别名是类名)
  type-aliases-package: com.yicao.pmiapi.pojo
  configuration:
    #自动驼峰命名
    map-underscore-to-camel-case: false